### ISSUE TITLE
Idea: Click through locked frame

### ISSUE THREAD

**Issue by dylanparry** [FerranVGithub/ItemFramer#3]
I was wondering if it would be possible to change the behaviour of locked frames so that you can click straight through them? This would make it useful for labelling chests for example as I would no longer have to guess where the invisible frames end and the chest begins. Thanks :)

**Comment by FerranVGithub** [comment]
Yeah I've already looked into it but I don't think I can remove the hitbox of the item frame with a datapack, I have however found this mod which might be useful for you.
https://modrinth.com/mod/click-through-updated

If I do find a way to do it within the datapack I will let you know.

**Comment by dylanparry** [comment]
That's a shame. Thanks for the link to the other mod though, I'll take a look at it 👍

**Comment by dylanparry** [comment]
That mod works great for what I wanted, and appears to be completely compatible with your datapack, so thanks again!

**Comment by FerranVGithub** [comment]
Sorry for bothering you again, but would you think a feature that'd go something like shift+right_clicking  resets the item rotation back to default could be cool? Cause if so I might look into doing so.

**Comment by FerranVGithub** [comment]
I've now done so. You can check it out for yourself if you want to. Pushed it to Modrinth a second ago.
